- src/00/package.devc.xml
- src/01/01/package.devc.xml
- src/01/01/z2ui5_if_selscreen_group.intf.abap
- src/01/02/package.devc.xml
- src/01/package.devc.xml
- src/02/package.devc.xml
- src/02/z2ui5_cl_http_handler.clas.locals_imp.abap
- src/90/package.devc.xml
- src/90/z2ui5_cl_app_demo_08.clas.abap
- src/90/z2ui5_cl_app_demo_09.clas.abap
Apart from Demo 07 which is commented out, all other demos pass my smoke tests
> Update on premise to current version

- abaplint.jsonc
this will fix the `Not a structure, FieldChain (check_syntax)` false positives
> update to 2302

- src/z2ui5_cl_http_handler.clas.locals_imp.abap
refactoring of the trans_ref_tab_2_tab( ) method signature, so I am submitting all changes for review
> Update to current version on-premise

- abaplint.jsonc
plus cleanup abaplint configuration
> exempt i_mv_editor from unused var check

- abaplint.jsonc
- src/00/z2ui5_cl_app_demo_06.clas.abap
- src/00/z2ui5_cl_app_demo_21.clas.abap
- src/z2ui5_cl_http_handler.clas.locals_imp.abap
> fix double space findings

- .gitignore
- abaplint-downport.jsonc
- package-lock.json
- package.json
prerequsites: Node 16 & Bash installed locally
run with `npm install && npm run downport`
> add script setup for running downport logic

- src/z2ui5_cl_xml_view.clas.abap
New TreeTable control
API Reference: sap.ui.table.TreeTable
> New TreeTable control

- src/z2ui5_cl_xml_view.clas.abap
1) Filter Bar:
API Reference:
sap.ui.comp.filterbar.FilterBar
2) Flexible Column Layout
API Reference:
sap.f.FlexibleColumnLayout
> New controls: FilterBar, FlexibleColumnLayout

- src/z2ui5_cl_xml_view.clas.abap
API Reference:
sap.ui.table.TreeTable
New parameters for TreeTable and TreeColumn
> TreeTable: new parameters

- src/z2ui5_cl_xml_view.clas.abap
( n = `xmlns:fb`   v = `sap.ui.comp.filterbar` )
> FilterBar: Namespace was missing

- src/z2ui5_cl_xml_view.clas.abap
sap.f.FlexibleColumnLayout: - aggregations are missing:
beginColumnPages
midColumnPages
endColumnPages
> FlexibleColumnLayout - aggregations are missing

- src/z2ui5_cl_xml_view.clas.abap
Property maxSuggestionWidth of class sap.m.Input added to abap method z2ui5_cl_xml_view->input
> add maxSuggestionWidth to input method

- src/z2ui5_cl_xml_view.clas.abap
added to view class:
radiobutton + rowactiontemplate
> radiobutton + rowactiontemplate

- src/z2ui5_cl_http_handler.clas.locals_imp.abap
- src/z2ui5_cl_xml_view.clas.abap
add new controls and a way to work with deep tables
> add sap.m.Tree & sap.m.StandardTreeItem

- src/z2ui5_cl_xml_view.clas.abap
Hi ,
I use the code based editor. I hope it is better.
Best Regards
Thomas
> UI Elemets IconTabBar + IconTabFilter

- src/z2ui5_cl_xml_view.clas.abap
id property for table + ui_table
export_spreadsheet CC (add a button)
> Export table to spreadsheet CC

- src/z2ui5_cl_xml_view.clas.abap
added support sap.m.table export to xlsx
new gantt chart components added (work in progress for the demo)
> view update - export to xlsx - first gantt compone

- src/z2ui5_cl_xml_view.clas.abap
sap.m.input: fieldWidth property
> sap.m.input: fieldWidth property

- src/z2ui5_cl_http_handler.clas.abap
added generic way creating date object in XML view
1. added onInit in controller
2. added Date.createObject global symbol
> added generic way creating date object in XML view

- src/z2ui5_cl_http_handler.clas.abap
added
1. createObject => create object from pattern: YYYY-MM-DDTHH:mm:ss
2. abapTimestampToDate 
3.abapDateToDateObject => pattern: YYYYMMDD
4. abapDateTimeToDateObject => accept 2 variabls: 1. DATE: YYYYMMDD       2. TIME: HHmmss - optional just for error handling
> abap to js date object

- src/z2ui5_cl_xml_view.clas.abap
> gantt chart base shape

- src/00/z2ui5_cl_fw_handler.clas.abap
t_arg fix when receiving non string value
> t_arg fix when receiving non string value

- src/z2ui5_cl_xml_view.clas.abap
https://sapui5.hana.ondemand.com/#/entity/sap.tnt.ToolPage/sample/sap.tnt.sample.ToolPageHorizontalNavigation/code
> Added ToolPage

- src/z2ui5_cl_xml_view.clas.abap
> Responsive Splitter

- src/z2ui5_cl_xml_view.clas.abap
a first take on dynamic generate shlp dialog
> dynamic generate shlp dialog

- src/z2ui5_cl_xml_view.clas.abap
added ircontroller parameter to method in order to get the current app object
> fix zcc_generate_ddic_shlp

- src/z2ui5_cl_xml_view.clas.abap
combobox
multi_input
radio button
radial micro chart (*fixed spelling error)
date_picker
input
> add new properties for controls

- src/z2ui5_cl_xml_view.clas.abap
AreaMicroChart
BulletMicroChart
ColumnMicroChart
ComparisonMicroChart
DeltaMicroChart
HarveyBallMicroChart
LineMicroChart
StackedBarMicroChart
> add micro charts to xml view WIP

- src/z2ui5_cl_fw_http_handler.clas.abap
- src/z2ui5_cl_xml_view.clas.abap
added <!DOCTYPE html> to http handler class
in order to support rich text editor TinyMCE.
add rich text editor + demo 106
> added doctype tag to http handler + rich text edit

- src/z2ui5_cl_xml_view.clas.abap
- new property "checkDirectUpload"
> zcc_file_uploader with new optional parameters

- src/z2ui5_cl_xml_view.clas.abap
update uploadset
update mask input
side panel
> add controls to xml view

- src/z2ui5_cl_xml_view.clas.abap
> new control xml view

- src/z2ui5_cl_xml_view.clas.abap
New parameters for dialog control:
-horizontalScrolling
-verticalScrolling
> New parameters for dialog control

- src/z2ui5_cl_xml_view.clas.abap
[sap.suite.ui.commons.Timeline](https://sapui5.hana.ondemand.com/api/sap.suite.ui.commons.Timeline)
> New timeline control

- src/z2ui5_cl_xml_view.clas.abap
https://sapui5.hana.ondemand.com/1.119.1/#/entity/sap.m.SplitContainer/sample/sap.m.sample.SplitContainer
> side container + updates

- src/z2ui5_cl_xml_view.clas.abap
New ValueState related properties
> New properties for TEXTAREA control

- src/01/z2ui5_cl_fw_cc_factory.clas.abap
- src/z2ui5_cl_fw_font_awsome_icons.clas.abap
- src/z2ui5_cl_fw_font_awsome_icons.clas.xml
will make a guide how the resources should be handled..
> font awsome free icons support

- src/01/z2ui5_cl_cc_driver_js.clas.abap
- src/z2ui5_cl_fw_http_handler.clas.abap
- src/z2ui5_cl_xml_view.clas.abap
now support js events as parameters
added highlight function.
performence & logic fixes
> driverjs update

- src/z2ui5_cl_fw_http_handler.clas.abap
If the optional parameter ARGS[3] is equal "EXT" than the new app will be called in new window (browser tab)
> Cross Application Navigation to external window

- src/z2ui5_cl_xml_view.clas.abap
https://github.com/abap2UI5/abap2UI5/issues/661
> add control sap.m.SuggestionItem

- src/z2ui5_cl_fw_http_handler.clas.abap
added setSizeLimit to json model as a parameter of HTTP_GET method.. default to 100 (as SAPUI5 Model default).
for now, used in oView, oViewNest, oViewNest2
need to add oViewPopup & oViewPopover (&fragment)
as continue to #496
> json model size limit parameter to http handler

- src/02/z2ui5_cl_cc_file_uploader.clas.abap
> add file uploader properties

- src/00/z2ui5_cl_util_func.clas.abap
- src/01/01/z2ui5_cl_fw_binding.clas.abap
- src/01/01/z2ui5_cl_fw_client.clas.abap
- src/01/01/z2ui5_cl_fw_model.clas.abap
- src/01/01/z2ui5_if_client.intf.abap
- src/02/z2ui5_cl_cc_chartjs.clas.abap
- src/10/01/z2ui5_cl_xml_view_cc.clas.abap
> update chartjs CC + binding logic - add compress

- src/00/z2ui5_cl_util_func.clas.abap
- src/00/z2ui5_cl_util_func.clas.testclasses.abap
> Fix trimming of horizontal tabs

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
For ObjectListItem:
- added event "press"
- added property "selected"
P.S.: Keep up the great work!
> Property and event for ObjectListItem

- src/01/02/z2ui5_cl_core_http_get.clas.abap
- src/01/05/z2ui5_cl_cc_message_manager.clas.abap
- src/01/05/z2ui5_cl_cc_message_manager.clas.xml
- src/02/01/01/z2ui5_cl_xml_view.clas.abap
- src/02/01/01/z2ui5_cl_xml_view_cc.clas.abap
> fix preproccesors & remove messagemanager.

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
- test/abap_transpile.json
> added template if, else, elseif, then, with, repea

- src/01/03/z2ui5_cl_core_app_search.clas.locals_imp.abap
New link: Generic DDIC searchhelp
> New link: Generic DDIC searchhelp

- src/02/01/01/z2ui5_cl_xml_view_cc.clas.abap
New Properties to Control FileUploader
> FileUploader

- src/01/02/z2ui5_cl_core_http_get.clas.abap
- src/02/01/01/z2ui5_cl_xml_view.clas.abap
1.
adjusted popup + popover fragment assign to sap.z2ui5.oViewPopup position in order to access view object before popup open (being able to run js on popup dom object before dialog open).
2. created a Fragment global var to get dom object as oViewPopup is not the actual view of the fragment, actually the oViewPopup is the dialog object from the popup.
> update http_get + add property to xml view

- src/01/01/z2ui5_cl_util_stmpncfctn.clas.abap
- src/01/03/z2ui5_cl_core_app_search.clas.abap
- src/01/03/z2ui5_cl_core_app_startup.clas.abap
> Improve class F4 dialog - add class description

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Added new property to UI_ROW_ACTION_ITEM
> UI_ROW_ACTION_ITEM Property Visible

- src/01/02/z2ui5_cl_core_http_get.clas.abap
- src/02/01/01/z2ui5_cl_xml_view.clas.abap
add setTimeout for follow_up_action, in order to finish set promises by controls.
update xml view
> add setTimeout for follow_up_action & update xml v

- src/01/02/z2ui5_cl_core_http_get.clas.abap
- src/01/04/z2ui5_cl_fw_cc_debugging_tools.clas.abap
- src/02/01/01/z2ui5_cl_xml_view.clas.abap
1. fallback for popover openById in http_get claSS
2. update xml view class
3. corrected debugging cc logic upon errors.xml
> various updates

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Add Routes and legends for Map
> Update Analytical Map

- src/01/02/z2ui5_cl_core_http_get.clas.abap
- src/01/05/z2ui5_cl_cc_message_manager.clas.abap
- src/01/05/z2ui5_cl_cc_spreadsheet.clas.abap
- src/02/z2ui5_if_client.intf.abap
update CC
add download B64 event frontend
> few updaes + download b64 file event client functi

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Add some missing properties to line chart, donut chart, and bar chart.
> add properties to charts

- src/01/05/z2ui5_cl_cc_spreadsheet.clas.abap
- src/02/01/01/z2ui5_cl_xml_view_cc.clas.abap
add column config array to custom control as a binded table instead of local json string. (not breaking - kept the previous implementation version active as well)
> spreadsheet columnconfig as a property of xml view

- src/01/02/z2ui5_cl_core_http_get.clas.abap
- src/01/05/z2ui5_cl_cc_imagemapster.clas.abap
- src/02/01/01/z2ui5_cl_xml_view.clas.abap
- src/02/z2ui5_if_client.intf.abap
> various changes

- src/01/02/z2ui5_cl_core_http_get.clas.abap
two_way param  binding based on param in core_types in http get method
> two_way  binding based on param in core_types

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Adding      subsequentSteps to WizardStep
> Wizard Branching Steps

- src/01/05/z2ui5_cl_cc_validator.clas.abap
- src/01/05/z2ui5_cl_cc_validator.clas.xml
as of work of Mauricio Lauffer
https://github.com/mauriciolauffer/openui5-validator/tree/master adapted by choper725
next up matching it with messaging control, as planned for this feature, using our messaging CC getting the errors in the backend
> form validator feature - WIP

- src/02/02/z2ui5_cl_pop_f4_help.clas.abap
> downport to 752 compatible syntax

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
> Enable Resizing for Step Input Control

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
> Enable Close Button and Custom Icons for Message Strip Control

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Added change Event on Slider UI
> Event on Slider Element

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Added Ui Element Date Range Selection
https://ui5.sap.com/#/entity/sap.m.DateRangeSelection/sample/sap.m.sample.DateRangeSelection/code
> Date Range Selection

- src/01/00/01/z2ui5_cl_ajson.clas.locals_imp.abap
- src/01/00/01/z2ui5_cl_ajson.clas.testclasses.abap
see [ajson#183](https://github.com/sbcgua/ajson/pull/183)
> Fix filter walk order for arrays (based on array index)

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Enables the possibility to add tile content
> Return correct reference at generic tile

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Added elements to the view class:
Side Navigation
Navigation List
Navigation List Item
Fixed Item
Added parameter id to the flex_box method
> Addition of the Side Navigation

- src/02/01/01/z2ui5_cl_xml_view.clas.abap
Add UI Element Color Picker
https://ui5.sap.com/#/api/sap.ui.unified.ColorPicker%23overview
https://ui5.sap.com/#/entity/sap.ui.unified.ColorPicker
> Update z2ui5_cl_xml_view.clas.abap: UI ColorPicker

- src/02/z2ui5_cl_xml_view.clas.abap
Addes Progress Indicator Property Visibility
> Progress Indicator Property Visibility

- src/01/02/z2ui5_cl_core_client.clas.abap
- src/01/02/z2ui5_cl_core_http_get.clas.abap
- src/01/02/z2ui5_cl_core_http_post.clas.abap
- src/01/02/z2ui5_if_core_types.intf.abap
- src/02/z2ui5_cl_http_handler.clas.abap
- src/02/z2ui5_if_client.intf.abap
- src/02/z2ui5_if_types.intf.abap
1. Added Component support in order to use Component.destroy()
TODO refactoring sap.z2ui5 and view handling -> instead of .placeAt use mainView of component manifest
Open for discussion -> make use of routing?
⚠️ please note that Session termination is implemented in Component.destroy and only will be triggered when we transitioned to Manifest View linkage instead of explicit placeAt (maybe lets open a dedicated Issue?)
1. Added Session Stateful support
*add the following lines to your REST handler in order to support stateful session handling*
```abap
if attributes-stateful-switched = abap_true.
server->set_session_stateful( stateful = attributes-stateful-active ).
endif.
```
And here is an ABAP example class for testing session handling
```abap
"! <p class="shorttext synchronized" …
```
> Added Component and Session Stateful Handling

- src/01/02/z2ui5_cl_core_http_get.clas.abap
Added Component support, integrated abap2ui5 view into rootview of component to participate on the standard lifecycle
see #1327
> Refactoring due to added Component support, slightly fixed session handl

- src/02/z2ui5_cl_xml_view.clas.abap
https://ui5.sap.com/#/api/sap.uxap.ObjectPageSubSection%23aggregations
> Added moreBlocks

- src/02/z2ui5_cl_xml_view.clas.abap
New parameter for multi_input.
Parameter name: visible
> New parameter for multi_input

- src/02/z2ui5_cl_xml_view.clas.abap
Prerequisite for SAP Sample: Grid List - Drag and Drop
> Added GridList with Drag and Drop functionality

- src/02/z2ui5_cl_xml_view.clas.abap
new Item HarveyBallMicroChartItem
> HarveyBallMicroChartItem

- src/02/z2ui5_cl_xml_view.clas.abap
> Properties for analytic_map

- src/02/z2ui5_cl_xml_view.clas.abap
Addition and correction comparison_micro_chart 
Sample
DATA(lo_comparison) = page->comparison_micro_chart(
*  EXPORTING
*                                                           colorpalette =
*                                                           press    =
size     = 'L'
*                                                           height   =
maxvalue = '100'
*                                                           minvalue =
*                                                           scale    =
*                                                           width    =
*                                                           hideonnodata =
*                                                           shrinkable =
*                                                           view …
> Correction of comparison_micro_chart and add comparison_micro_chart_data

- src/02/z2ui5_cl_xml_view.clas.abap
List of methods:
VIZ_FRAME
VIZ_DATASET
VIZ_FLATTENED_DATASET
VIZ_DIMENSIONS
VIZ_DIMENSION_DEFINITION
VIZ_MEASURES
VIZ_MEASURE_DEFINITION
VIZ_FEEDS
VIZ_FEED_ITEM
> New VizFrame Chart control

- app/webapp/controller/View1.controller.js
- src/01/03/z2ui5_cl_app_view1_js.clas.abap
- src/02/z2ui5_if_client.intf.abap
Added URLHelper Methods redirect, triggerEmail, triggerSms and triggerTel
> Added URLHelper Methods

- app/webapp/controller/View1.controller.js
- src/02/z2ui5_if_client.intf.abap
Enabling Navigation for Popover
> Popover Navigation

- app/webapp/cc/DebugTool.js
- src/01/03/z2ui5_cl_app_debugtool_js.clas.abap
> prettify debug view popover xml

- app/webapp/Component.js
- app/webapp/cc/DebugTool.js
- src/01/03/z2ui5_cl_app_component_js.clas.abap
- src/01/03/z2ui5_cl_app_debugtool_js.clas.abap
Before this fix closing the debug popup with the close button was broken. Reopen required to press `CTRL+F12` twice.
> fix broken debug view close

- src/02/01/z2ui5_cl_pop_input_val.clas.abap
If Cancel was clicked was not transferred
> Mini Bug in Poup

- src/02/01/z2ui5_cl_pop_bal.clas.abap
sample Z2UI5_CL_DEMO_APP_154
before
after
> improve BAL message popup

- src/01/02/z2ui5_cl_core_srv_attri.clas.abap
> fix conv exit serial error

- app/webapp/controller/App.controller.js
- app/webapp/controller/View1.controller.js
- src/01/03/z2ui5_cl_app_app_js.clas.abap
- src/01/03/z2ui5_cl_app_view1_js.clas.abap
- src/02/z2ui5_cl_xml_view_cc.clas.abap
- src/02/z2ui5_if_client.intf.abap
https://sapui5.hana.ondemand.com/#/api/module:sap/ui/util/Storage
> added local and session storage functionality

- src/02/z2ui5_cl_xml_view.clas.abap
Implemented tree table extension.
> Update z2ui5_cl_xml_view.clas.abap / tree_extension

- app/webapp/controller/App.controller.js
- src/01/03/z2ui5_cl_app_app_js.clas.abap
handle sorts
return the value to the filtered column
add filter icon & sort icon once applied
> uitableext handle sort & filter with icons and return value

- src/00/03/z2ui5_cl_util_abap.clas.abap
> Possibility to save without TR

- app/webapp/controller/App.controller.js
> fix dirty for OpenUI5

- src/02/z2ui5_cl_app_startup.clas.abap
- src/02/z2ui5_cl_exit.clas.abap
> add user exit to system info popup
