abap2UI5/abap2UI5

src/z2ui5_cl_http_handler.clas.locals_imp.abap
When using a flat structure for the screen for example:
no binding is happening for any of the fields.
I tracked the issue to the method get_t_attri_by_ref in local class z2ui5_lcl_utility of class Z2UI5_CL_HTTP_HANDLER change in the PR, the dynamic parser was only working for cl_abap_classdescr=>typekind_struct2 which is deep structure, but not for cl_abap_classdescr=>typekind_struct1 which is flat structure.
=> adding logic for typekind_struct1

src/z2ui5_cl_http_handler.clas.locals_imp.abap
set needed, https://rules.abaplint.org/unused_variables/
=> `io_app` used dynamically

src/00/package.devc.xml
Adds BOM to `package.devc.xml` to avoid diff for on-prem
Closes #133
PS: If you need to create an XML for another object, it's best to start with a copy of an existing XML-file and upload it to GH. When you edit it afterwards, the format (BOM) will be retained.
=> Avoid diff for package

src/z2ui5_cl_http_handler.clas.locals_imp.abap
```like ref to value``` which is ref to data is not a valid syntax in older releases ( <= 7.40 )
=> fix-syntax-issue-in-older-releases

src/z2ui5_cl_http_handler.clas.locals_imp.abap
as workaround for transpiler/open-abap bug
=> call the non-aliased method for UUID

README.md
This is a proposal to disable caching for resources served by the `GET` handler. All the generated views (and especially the index file) should always be retrieved from the server. 
⚠ I have no way of testing in an ABAP Cloud environment, so I only enhanced the documentation section for on-premise.
=> disable caching of abap2ui5 resources

abaplint.jsonc, src/z2ui5_cl_xml_view.clas.abap
not working with EMPTY KEY decleration in TT of method zfc_ddic_search_help
changed to DEFAULT KEY
=> fix zfc_ddic_search_help TT declerations

src/z2ui5_cl_xml_view.clas.abap
Method multi_combobox was using the generic "ComboBox" instead of "MultiComboBox".
=> MultiComboBox fix

src/00/z2ui5_cl_util_func.clas.abap
Fix this dump on S/4 HANA 2022 SP02
=> Downport rtti_get_classes_impl_intf

src/02/03/z2ui5_cl_popup_to_select.clas.abap
Add `sort_field` and `descending` parameters and make sorter work.
This looks like a leftover from the past
```ABAP
sorter : { path : 'STORAGE_LOCATION', descending : false }
```
usage example:
```ABAP
mt_tab = VALUE #( descr = 'this is a description'
(  title = 'title_01'  value = 'value_01' )
(  title = 'title_02'  value = 'value_02' )
(  title = 'title_03'  value = 'value_03' )
(  title = 'title_04'  value = 'value_04' )
(  title = 'title_05'  value = 'value_05' ) ).
DATA(lo_app) = z2ui5_cl_popup_to_select=>factory(
i_tab        = mt_tab
i_title      = 'any title'
i_sort_field = 'value'
i_descending = abap_true  ).
client->nav_app_call( lo_app ).
```
=> popup_to_select: fix sorter + parameterize

src/01/02/z2ui5_cl_core_http_get.clas.abap, src/01/04/z2ui5_cl_fw_cc_debugging_tools.clas.abap, src/01/05/z2ui5_cl_cc_chartjs.clas.abap
1. removed meta model name from preprocessors model in http_get. meaning no need to bind {meta>/} yet {/} is enough, once useing template preprocessor.
2. add logic to debbuger to identify once templating is being used and view xml source after templating
before templating:
after:
3. decode > in xml output of debugger.
=> update xml templating model binding & debugger feature for templating

src/01/01/z2ui5_cl_util_api.clas.abap
If class has syntax error cx_sy_rtti_syntax_error is raised and propagated.
With this fix we catch it and deal with it as the class doesn't exist.
=> catch cx_sy_rtti_syntax_error

src/01/00/02/z2ui5_cl_stmpncfctn_api.clas.abap
Fixes CX_SY_DYN_CALL_ILLEGAL_TYPE error on S/4HANA systems
=> Fix CX_SY_DYN_CALL_ILLEGAL_TYPE

src/02/01/01/z2ui5_cl_xml_view.clas.abap
Added Parameters
startvalue and endvalue are no properties of rangeSlider.     
https://sapui5.hana.ondemand.com/sdk/#/api/sap.m.RangeSlider%23overview
=> RangeSlider Parameters

src/02/01/01/z2ui5_cl_xml_view.clas.abap
Although the property id cannot be found in the official documentation for the OverflowToolbarButton, by adding it you can now also use functions that require an ID, such as the Action Sheet.
=> Added property id to OverflowToolbarButton

src/01/02/z2ui5_cl_core_client.clas.abap, src/01/02/z2ui5_cl_core_http_get.clas.abap, src/01/02/z2ui5_if_core_types.intf.abap, src/02/03/z2ui5_if_client.intf.abap
This is a first try to implement kind of data loss protection, which triggers this popup when browser back or reload button is pressed, or FLP back navigation is used. 
Therefore I introduced a new method `z2ui5_if_client~dirty` and a new flag `dirty` which can be used to set the page dirty.
Note that we use `sap.ushell.Container.setDirtyFlag` while running in shell context, e.g. FLP, and `window.onbeforeunload` when running standalone. 
As I'm not too familiar with the inner workings of abap2UI5 I have know clue whether that's the right way to do it. Feel free to improve.
See also demo app z2ui5_cl_demo_app_279.
fixes #1348
=> Data loss protection with dirty flag

src/02/01/z2ui5_cl_pop_to_select.clas.abap
New optional parameter `multiselect` of `z2ui5_cl_pop_to_select=>factory` to enable selection of multiple entries. In this case the field `table` of the result structure is filled instead of `row`.
sample z2ui5_cl_demo_app_152 update here
https://github.com/abap2UI5/abap2UI5-samples/pull/362
=> Popup to select: New feature multiselect

app/webapp/Component.js, app/webapp/cc/DebugTool.js, src/01/03/z2ui5_cl_app_component_js.clas.abap, src/01/03/z2ui5_cl_app_debugtool_js.clas.abap
Before this change it was possible to open multiple debug windows by pressing CTRL+F12 several times. 
After this change only one debug popup can be opened, pressing CTRL+F12 again closes the debug popup.
=> enable toggle debug popup

src/02/z2ui5_cl_xml_view.clas.abap
The new method ROW_SETTINGS represents sap.ui.table.RowSettings. This can be used for row highlighting in sap.ui.table.
=> New method ROW_SETTINGS

src/01/02/z2ui5_cl_core_srv_model.clas.abap
If an object in a Subapp differs from the object in another Subapps. Bining will rasie an error, without checking and reseting MT_ATTRI first.
=> Error in Subapp binding
